# Generated by Django 4.2 on 2023-04-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_branch_alter_menu_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['level', 'branch', 'title'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
